### ISSUE TITLE
VSCode: Components should be highlighted with a different color

### ISSUE THREAD

**Issue by RafidMuhymin** [snowpackjs/astro-language-tools#4]
### What package manager are you using?

yarn

### What operating system are you using?

Windows

### Describe the Bug

Components are highlighted with the same color as general HTML codes.

### Steps to Reproduce

Components should be highlighted with a different color.

**Comment by matthewp** [comment]
Ah, reopening as this doesn't seem to work when you close the element with an end tag.

**Comment by matthewp** [comment]
Fixed in https://github.com/snowpackjs/astro-language-tools/pull/42
