### ISSUE TITLE
VSCode : Peek Definitions

### ISSUE THREAD

**Issue by aFuzzyBear** [snowpackjs/astro-language-tools#8]
### Background & Motivation

This is something I do, when I spend most of my time just reading code, is peeking into the source files for API's to see whats under the hood.

This would also be a nice feature to have with the Astro Language extension, where it would apply to looking up components and functions written in the body of the astro file and in the frontmatter block

### Open Questions

I truly dont know enough to make any suggestions regarding a solution for this particular problem, 

### Detailed Design

This is the reference to the VSCode docs that describes the feature in more detail:

https://code.visualstudio.com/docs/editor/editingevolved#_peek

And the reference to the API 

https://code.visualstudio.com/api/references/vscode-api#DefinitionProvider

I also noticed that this API could be related to the request snowpackjs/astro#1024 and a bit wider afield where we can define the symbols used in the astro files, this can help with the Outline dialog box in the editor window of VSCode

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [X] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by matthewp** [comment]
This is now supported!

<img width="1186" alt="Screen Shot 2021-09-09 at 4 09 02 PM" src="https://user-images.githubusercontent.com/361671/132755465-8331c0d0-4d88-46e0-92d6-352eeecbe2af.png">

**Comment by aFuzzyBear** [comment]
Love it dude!!! thanks man,
